### ISSUE TITLE
Enhancement on dep versions

### ISSUE THREAD

**Issue by YBoy-git** [rybmks/sync-postgres-test#5]
I've recently stuck to a charming dep version style.

For example
```toml
serde_json = "1"  # instead of 1.0
postgres = "0.19" # instead of 0.19.8
```

The idea is to use only the major segment for deps with `major>=1`, and major+minor `for major==0`

In this way, we get rid of the useless patch segment, which does not provide any useful info.
